
default: &default
  adapter: postgresql
  encoding: unicode
  host:     localhost
  username: postgres
  password: postgres
  port:     5432
  pool:     5
  timeout: 5000

development:
 <<: *default
 database: chat_app_development

production: &production
 <<: *default
 database: chat_app_production

test:
  <<: *default
  database: chat_app_test
